/** Auto-generated from CSV Propfirm Rules/Day Traders Rules.csv — run: `npm run gen:daytraders-funded` */

export type DaytradersFundedCsvRow = {
  program: string;
  size: string;
  overnight: string;
  tradingNews: string;
  sizingFunded: string;
  drawdownTypeFunded: string;
  maxDrawdownFundedUsd: number;
  dllFunded: string;
  /** null = pas de phase buffer (CSV vide / tiret). */
  bufferUsd: number | null;
  consistencyLabel: string;
  minTradingDays: string;
  minProfitPerDay: string;
  payoutMiniUsd: number;
  /** null = pas de plafond explicite (ex. No limit). */
  payoutMaxUsd: number | null;
  /** Part du profit/surplus prise en compte pour le montant indicatif (ex. 0.8 pour 80 % CSV). */
  profitSplitFraction: number;
  profitSplitLabel: string;
  payoutRulesBrief: string;
};

export const DAYTRADERS_FUNDED_FROM_CSV: Record<string, DaytradersFundedCsvRow> = {
  "DayTraders Core Plan|50k": {
    program: "DayTraders Core Plan",
    size: "50k",
    overnight: "No",
    tradingNews: "Yes",
    sizingFunded: "1 minis / 10 micros",
    drawdownTypeFunded: "Trailing",
    maxDrawdownFundedUsd: 2000,
    dllFunded: "$1 000",
    bufferUsd: 1000,
    consistencyLabel: "-",
    minTradingDays: "-",
    minProfitPerDay: "-",
    payoutMiniUsd: 0,
    payoutMaxUsd: null,
    profitSplitFraction: 0.8,
    profitSplitLabel: "80%",
    payoutRulesBrief: "—",
  },
  "DayTraders EOD|150k": {
    program: "DayTraders EOD",
    size: "150k",
    overnight: "No",
    tradingNews: "Yes",
    sizingFunded: "12 minis / 120 micros",
    drawdownTypeFunded: "EOD",
    maxDrawdownFundedUsd: 4000,
    dllFunded: "$2 000",
    bufferUsd: 5100,
    consistencyLabel: "30%",
    minTradingDays: "8",
    minProfitPerDay: "$300",
    payoutMiniUsd: 500,
    payoutMaxUsd: 3500,
    profitSplitFraction: 1,
    profitSplitLabel: "100%",
    payoutRulesBrief: "30% · 8 · $300",
  },
  "DayTraders EOD|25k": {
    program: "DayTraders EOD",
    size: "25k",
    overnight: "No",
    tradingNews: "Yes",
    sizingFunded: "6 minis / 60 micros",
    drawdownTypeFunded: "EOD",
    maxDrawdownFundedUsd: 1000,
    dllFunded: "$800",
    bufferUsd: 1600,
    consistencyLabel: "30%",
    minTradingDays: "8",
    minProfitPerDay: "$100",
    payoutMiniUsd: 500,
    payoutMaxUsd: 1000,
    profitSplitFraction: 1,
    profitSplitLabel: "100%",
    payoutRulesBrief: "30% · 8 · $100",
  },
  "DayTraders EOD|300k": {
    program: "DayTraders EOD",
    size: "300k",
    overnight: "No",
    tradingNews: "Yes",
    sizingFunded: "40 minis / 400 micros",
    drawdownTypeFunded: "EOD",
    maxDrawdownFundedUsd: 6500,
    dllFunded: "$3 250",
    bufferUsd: 7600,
    consistencyLabel: "30%",
    minTradingDays: "8",
    minProfitPerDay: "$400",
    payoutMiniUsd: 500,
    payoutMaxUsd: 5000,
    profitSplitFraction: 1,
    profitSplitLabel: "100%",
    payoutRulesBrief: "30% · 8 · $400",
  },
  "DayTraders EOD|50k": {
    program: "DayTraders EOD",
    size: "50k",
    overnight: "No",
    tradingNews: "Yes",
    sizingFunded: "10 minis / 100 micros",
    drawdownTypeFunded: "EOD",
    maxDrawdownFundedUsd: 2000,
    dllFunded: "$1 250",
    bufferUsd: 2600,
    consistencyLabel: "30%",
    minTradingDays: "8",
    minProfitPerDay: "$200",
    payoutMiniUsd: 500,
    payoutMaxUsd: 2000,
    profitSplitFraction: 1,
    profitSplitLabel: "100%",
    payoutRulesBrief: "30% · 8 · $200",
  },
  "DayTraders Edge Plan|150k": {
    program: "DayTraders Edge Plan",
    size: "150k",
    overnight: "No",
    tradingNews: "Yes",
    sizingFunded: "2 minis / 20 micros",
    drawdownTypeFunded: "Trailing",
    maxDrawdownFundedUsd: 4500,
    dllFunded: "$1 750",
    bufferUsd: 1000,
    consistencyLabel: "-",
    minTradingDays: "-",
    minProfitPerDay: "-",
    payoutMiniUsd: 0,
    payoutMaxUsd: null,
    profitSplitFraction: 0.8,
    profitSplitLabel: "80%",
    payoutRulesBrief: "—",
  },
  "DayTraders S2F|150k": {
    program: "DayTraders S2F",
    size: "150k",
    overnight: "No",
    tradingNews: "Yes",
    sizingFunded: "24 minis / 240 micros",
    drawdownTypeFunded: "EOD",
    maxDrawdownFundedUsd: 6000,
    dllFunded: "$3 750",
    bufferUsd: null,
    consistencyLabel: "20%",
    minTradingDays: "10",
    minProfitPerDay: "$300",
    payoutMiniUsd: 500,
    payoutMaxUsd: 3000,
    profitSplitFraction: 1,
    profitSplitLabel: "100%",
    payoutRulesBrief: "20% · 10 · $300",
  },
  "DayTraders S2F|25k": {
    program: "DayTraders S2F",
    size: "25k",
    overnight: "No",
    tradingNews: "Yes",
    sizingFunded: "2 minis / 20 micros",
    drawdownTypeFunded: "EOD",
    maxDrawdownFundedUsd: 1000,
    dllFunded: "-",
    bufferUsd: null,
    consistencyLabel: "20%",
    minTradingDays: "10",
    minProfitPerDay: "$100",
    payoutMiniUsd: 500,
    payoutMaxUsd: 1000,
    profitSplitFraction: 1,
    profitSplitLabel: "100%",
    payoutRulesBrief: "20% · 10 · $100",
  },
  "DayTraders S2F|50k": {
    program: "DayTraders S2F",
    size: "50k",
    overnight: "No",
    tradingNews: "Yes",
    sizingFunded: "10 minis / 100 micros",
    drawdownTypeFunded: "EOD",
    maxDrawdownFundedUsd: 2500,
    dllFunded: "$1 250",
    bufferUsd: null,
    consistencyLabel: "20%",
    minTradingDays: "10",
    minProfitPerDay: "$200",
    payoutMiniUsd: 500,
    payoutMaxUsd: 2000,
    profitSplitFraction: 1,
    profitSplitLabel: "100%",
    payoutRulesBrief: "20% · 10 · $200",
  },
  "DayTraders Static|100k": {
    program: "DayTraders Static",
    size: "100k",
    overnight: "No",
    tradingNews: "Yes",
    sizingFunded: "8 minis / 80 micros",
    drawdownTypeFunded: "Static",
    maxDrawdownFundedUsd: 1500,
    dllFunded: "-",
    bufferUsd: 3100,
    consistencyLabel: "30%",
    minTradingDays: "8",
    minProfitPerDay: "$300",
    payoutMiniUsd: 500,
    payoutMaxUsd: 3000,
    profitSplitFraction: 1,
    profitSplitLabel: "100%",
    payoutRulesBrief: "30% · 8 · $300",
  },
  "DayTraders Static|150k": {
    program: "DayTraders Static",
    size: "150k",
    overnight: "No",
    tradingNews: "Yes",
    sizingFunded: "8 minis / 80 micros",
    drawdownTypeFunded: "Static",
    maxDrawdownFundedUsd: 1750,
    dllFunded: "-",
    bufferUsd: 5100,
    consistencyLabel: "30%",
    minTradingDays: "8",
    minProfitPerDay: "$300",
    payoutMiniUsd: 500,
    payoutMaxUsd: 3500,
    profitSplitFraction: 1,
    profitSplitLabel: "100%",
    payoutRulesBrief: "30% · 8 · $300",
  },
  "DayTraders Static|25k": {
    program: "DayTraders Static",
    size: "25k",
    overnight: "No",
    tradingNews: "Yes",
    sizingFunded: "2 minis / 20 micros",
    drawdownTypeFunded: "Static",
    maxDrawdownFundedUsd: 750,
    dllFunded: "-",
    bufferUsd: 1600,
    consistencyLabel: "30%",
    minTradingDays: "8",
    minProfitPerDay: "$100",
    payoutMiniUsd: 500,
    payoutMaxUsd: 1000,
    profitSplitFraction: 1,
    profitSplitLabel: "100%",
    payoutRulesBrief: "30% · 8 · $100",
  },
  "DayTraders Static|50k": {
    program: "DayTraders Static",
    size: "50k",
    overnight: "No",
    tradingNews: "Yes",
    sizingFunded: "6 minis / 60 micros",
    drawdownTypeFunded: "Static",
    maxDrawdownFundedUsd: 1000,
    dllFunded: "-",
    bufferUsd: 2600,
    consistencyLabel: "30%",
    minTradingDays: "8",
    minProfitPerDay: "$200",
    payoutMiniUsd: 500,
    payoutMaxUsd: 2000,
    profitSplitFraction: 1,
    profitSplitLabel: "100%",
    payoutRulesBrief: "30% · 8 · $200",
  },
  "DayTraders Trail|150k": {
    program: "DayTraders Trail",
    size: "150k",
    overnight: "No",
    tradingNews: "Yes",
    sizingFunded: "12 minis / 120 micros",
    drawdownTypeFunded: "Trailing",
    maxDrawdownFundedUsd: 4500,
    dllFunded: "-",
    bufferUsd: 5100,
    consistencyLabel: "30%",
    minTradingDays: "8",
    minProfitPerDay: "$300",
    payoutMiniUsd: 500,
    payoutMaxUsd: 3500,
    profitSplitFraction: 1,
    profitSplitLabel: "100%",
    payoutRulesBrief: "30% · 8 · $300",
  },
  "DayTraders Trail|25k": {
    program: "DayTraders Trail",
    size: "25k",
    overnight: "No",
    tradingNews: "Yes",
    sizingFunded: "6 minis / 60 micros",
    drawdownTypeFunded: "Trailing",
    maxDrawdownFundedUsd: 1500,
    dllFunded: "-",
    bufferUsd: 1600,
    consistencyLabel: "30%",
    minTradingDays: "8",
    minProfitPerDay: "$100",
    payoutMiniUsd: 500,
    payoutMaxUsd: 1000,
    profitSplitFraction: 1,
    profitSplitLabel: "100%",
    payoutRulesBrief: "30% · 8 · $100",
  },
  "DayTraders Trail|300k": {
    program: "DayTraders Trail",
    size: "300k",
    overnight: "No",
    tradingNews: "Yes",
    sizingFunded: "40 minis / 400 micros",
    drawdownTypeFunded: "Trailing",
    maxDrawdownFundedUsd: 7000,
    dllFunded: "-",
    bufferUsd: 7600,
    consistencyLabel: "30%",
    minTradingDays: "8",
    minProfitPerDay: "$400",
    payoutMiniUsd: 500,
    payoutMaxUsd: 5000,
    profitSplitFraction: 1,
    profitSplitLabel: "100%",
    payoutRulesBrief: "30% · 8 · $400",
  },
  "DayTraders Trail|50k": {
    program: "DayTraders Trail",
    size: "50k",
    overnight: "No",
    tradingNews: "Yes",
    sizingFunded: "10 minis / 100 micros",
    drawdownTypeFunded: "Trailing",
    maxDrawdownFundedUsd: 2500,
    dllFunded: "-",
    bufferUsd: 2600,
    consistencyLabel: "30%",
    minTradingDays: "8",
    minProfitPerDay: "$200",
    payoutMiniUsd: 500,
    payoutMaxUsd: 2000,
    profitSplitFraction: 1,
    profitSplitLabel: "100%",
    payoutRulesBrief: "30% · 8 · $200",
  },
  "DayTraders Ultra Plan|300k": {
    program: "DayTraders Ultra Plan",
    size: "300k",
    overnight: "No",
    tradingNews: "Yes",
    sizingFunded: "3 minis / 30 micros",
    drawdownTypeFunded: "Trailing",
    maxDrawdownFundedUsd: 7000,
    dllFunded: "$3 250",
    bufferUsd: 1000,
    consistencyLabel: "-",
    minTradingDays: "-",
    minProfitPerDay: "-",
    payoutMiniUsd: 0,
    payoutMaxUsd: null,
    profitSplitFraction: 0.8,
    profitSplitLabel: "80%",
    payoutRulesBrief: "—",
  },
};
